=== giammaleoni/Beyblade-X/json_schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Beyblade X",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "Nome completo": {
      "type": "string"
    },
    "Link immagine": {
      "type": "string",
      "format": "uri"
    },
    "Linea": {
      "type": "string"
    },
    "Tipo": {
      "type": "string",
      "enum": [
        "Attacco",
        "Difesa",
        "Resistenza",
        "Equilibrio"
      ]
    },
    "Direzione spin": {
      "type": "string",
      "enum": [
        "Left",
        "Right"
      ]
    },
    "Lama": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "Nome": {
          "type": "string"
        },
        "Linea": {
          "type": "string"
        },
        "Tipo": {
          "type": "string",
          "enum": [
            "Attacco",
            "Difesa",
            "Resistenza",
            "Equilibrio"
          ]
        },
        "Direzione spin": {
          "type": "string",
          "enum": [
            "Left",
            "Right"
          ]
        },
        "Attacco": {
          "type": "number"
        },
        "Difesa": {
          "type": "number"
        },
        "Resistenza": {
          "type": "number"
        }
      },
      "required": [
        "Nome",
        "Linea",
        "Tipo",
        "Direzione spin",
        "Attacco",
        "Difesa",
        "Resistenza"
      ]
    },
    "Cricchetto": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "Nome": {
          "type": "string",
          "pattern": "^[0-9]-[0-9]{2}$"
        },
        "Attacco": {
          "type": "number"
        },
        "Difesa": {
          "type": "number"
        },
        "Resistenza": {
          "type": "number"
        },
        "Altezza": {
          "type": "integer"
        }
      },
      "required": [
        "Nome",
        "Attacco",
        "Difesa",
        "Resistenza",
        "Altezza"
      ]
    },
    "Punta": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "Nome": {
          "type": "string",
          "enum": [
            "F",
            "T",
            "B",
            "N",
            "HN",
            "LF",
            "P",
            "O",
            "S",
            "R",
            "HT",
            "GF",
            "GB",
            "GP",
            "GN",
            "U",
            "C",
            "E",
            "TP",
            "M",
            "D",
            "A",
            "H",
            "DB",
            "MN",
            "G",
            "FB",
            "L",
            "BS",
            "LR",
            "UN",
            "Z",
            "J",
            "UF",
            "V",
            "LO",
            "W",
            "K",
            "GR",
            "Tr",
            "WB",
            "TK",
            "Op"
          ]
        },
        "Attacco": {
          "type": "number"
        },
        "Difesa": {
          "type": "number"
        },
        "Resistenza": {
          "type": "number"
        },
        "Propulsione": {
          "type": "number"
        },
        "Esplosione": {
          "type": "number"
        }
      },
      "required": [
        "Nome",
        "Attacco",
        "Difesa",
        "Resistenza",
        "Propulsione",
        "Esplosione"
      ]
    }
  },
  "required": [
    "Nome completo",
    "Linea",
    "Tipo",
    "Direzione spin",
    "Lama",
    "Cricchetto",
    "Punta"
  ]
}

=== giammaleoni/Beyblade-X/beyblades/buster_dran_5-70db.json
{
  "Nome completo": "Buster Dran 5-70DB",
  "Linea": "Unique Line",
  "Tipo": "Resistenza",
  "Direzione spin": "Right",
  "Lama": {
    "Nome": "Buster Dran",
    "Linea": "Unique Line",
    "Tipo": "Resistenza",
    "Direzione spin": "Right",
    "Attacco": 70,
    "Difesa": 20,
    "Resistenza": 10
  },
  "Cricchetto": {
    "Nome": "5-70",
    "Attacco": 12,
    "Difesa": 8.5,
    "Resistenza": 9.5,
    "Altezza": 70
  },
  "Punta": {
    "Nome": "DB",
    "Attacco": 15,
    "Difesa": 20,
    "Resistenza": 55,
    "Propulsione": 10,
    "Esplosione": 30
  }
}

=== giammaleoni/Beyblade-X/beyblades/shelter_drake_5-70o.json
{
  "Nome completo": "Shelter Drake 5-70O",
  "Linea": "Basic Line",
  "Tipo": "Resistenza",
  "Direzione spin": "Right",
  "Lama": {
    "Nome": "Shelter Drake",
    "Linea": "Basic Line",
    "Tipo": "Resistenza",
    "Direzione spin": "Right",
    "Attacco": 25,
    "Difesa": 40,
    "Resistenza": 35
  },
  "Cricchetto": {
    "Nome": "5-70",
    "Attacco": 12,
    "Difesa": 8.5,
    "Resistenza": 9.5,
    "Altezza": 70
  },
  "Punta": {
    "Nome": "O",
    "Attacco": 10,
    "Difesa": 30,
    "Resistenza": 50,
    "Propulsione": 10,
    "Esplosione": 30
  }
}

=== giammaleoni/Beyblade-X/beyblades/driger_slash_4-80p.json
{
  "Nome completo": "Driger Slash 4-80P",
  "Linea": "X-Over Project",
  "Tipo": "Equilibrio",
  "Direzione spin": "Right",
  "Lama": {
    "Nome": "Driger Slash",
    "Linea": "X-Over Project",
    "Tipo": "Equilibrio",
    "Direzione spin": "Right",
    "Attacco": 40,
    "Difesa": 35,
    "Resistenza": 25
  },
  "Cricchetto": {
    "Nome": "4-80",
    "Attacco": 11,
    "Difesa": 11,
    "Resistenza": 8,
    "Altezza": 80
  },
  "Punta": {
    "Nome": "P",
    "Attacco": 25,
    "Difesa": 25,
    "Resistenza": 25,
    "Propulsione": 25,
    "Esplosione": 80
  }
}

=== giammaleoni/Beyblade-X/beyblades/mosasaurus_9-60u.json
{
  "Nome completo": "Mosasaurus 9-60U",
  "Linea": "Jurassic World Collab",
  "Tipo": "Equilibrio",
  "Direzione spin": "Right",
  "Lama": {
    "Nome": "Mosasaurus",
    "Linea": "Jurassic World Collab",
    "Tipo": "Equilibrio",
    "Direzione spin": "Right",
    "Attacco": 32,
    "Difesa": 55,
    "Resistenza": 13
  },
  "Cricchetto": {
    "Nome": "9-60",
    "Attacco": 13,
    "Difesa": 10,
    "Resistenza": 7,
    "Altezza": 60
  },
  "Punta": {
    "Nome": "U",
    "Attacco": 25,
    "Difesa": 25,
    "Resistenza": 30,
    "Propulsione": 20,
    "Esplosione": 80
  }
}

=== giammaleoni/Beyblade-X/esempio_beyblade.json
{
  "Nome completo": "Sword Dran 3-60F",
  "Link immagine": "https://beycommunity.com/en/x/products/sword-dran/",
  "Linea": "Basic Line",
  "Tipo": "Attacco",
  "Direzione spin": "Right",
  "Lama": {
    "Nome": "Dran Sword",
    "Linea": "Basic Line",
    "Tipo": "Attacco",
    "Direzione spin": "Right",
    "Attacco": 55,
    "Difesa": 25,
    "Resistenza": 20
  },
  "Cricchetto": {
    "Nome": "3-60",
    "Attacco": 15,
    "Difesa": 9,
    "Resistenza": 6,
    "Altezza": 60
  },
  "Punta": {
    "Nome": "F",
    "Attacco": 40,
    "Difesa": 15,
    "Resistenza": 10,
    "Propulsione": 35,
    "Esplosione": 80
  }
}

=== giammaleoni/Beyblade-X/beyblades/t_rex_1-80gb.json
{
  "Nome completo": "T. Rex 1-80GB",
  "Linea": "Jurassic World Collab",
  "Tipo": "Resistenza",
  "Direzione spin": "Right",
  "Lama": {
    "Nome": "T. Rex",
    "Linea": "Jurassic World Collab",
    "Tipo": "Resistenza",
    "Direzione spin": "Right",
    "Attacco": 65,
    "Difesa": 30,
    "Resistenza": 5
  },
  "Cricchetto": {
    "Nome": "1-80",
    "Attacco": 7,
    "Difesa": 4,
    "Resistenza": 9,
    "Altezza": 80
  },
  "Punta": {
    "Nome": "GB",
    "Attacco": 10,
    "Difesa": 15,
    "Resistenza": 45,
    "Propulsione": 30,
    "Esplosione": 30
  }
}

=== giammaleoni/Beyblade-X/beyblades/obsidian_shell_4-60d.json
{
  "Nome completo": "Obsidian Shell 4-60D",
  "Linea": "Basic Line",
  "Tipo": "Difesa",
  "Direzione spin": "Right",
  "Lama": {
    "Nome": "Obsidian Shell",
    "Linea": "Basic Line",
    "Tipo": "Difesa",
    "Direzione spin": "Right",
    "Attacco": 10,
    "Difesa": 65,
    "Resistenza": 25
  },
  "Cricchetto": {
    "Nome": "4-60",
    "Attacco": 11,
    "Difesa": 15,
    "Resistenza": 6,
    "Altezza": 60
  },
  "Punta": {
    "Nome": "D",
    "Attacco": 10,
    "Difesa": 55,
    "Resistenza": 25,
    "Propulsione": 10,
    "Esplosione": 50
  }
}

=== giammaleoni/Beyblade-X/beyblades/yell_kong_3-60gb.json
{
  "Nome completo": "Yell Kong 3-60GB",
  "Linea": "Basic Line",
  "Tipo": "Resistenza",
  "Direzione spin": "Right",
  "Lama": {
    "Nome": "Yell Kong",
    "Linea": "Basic Line",
    "Tipo": "Resistenza",
    "Direzione spin": "Right",
    "Attacco": 13,
    "Difesa": 37,
    "Resistenza": 50
  },
  "Cricchetto": {
    "Nome": "3-60",
    "Attacco": 15,
    "Difesa": 9,
    "Resistenza": 6,
    "Altezza": 60
  },
  "Punta": {
    "Nome": "GB",
    "Attacco": 10,
    "Difesa": 15,
    "Resistenza": 45,
    "Propulsione": 30,
    "Esplosione": 30
  }
}
